### ISSUE TITLE
Memory not released in K8S (production environment)

### ISSUE THREAD

**Issue by JeremyVm** [QuestPDF/QuestPDF#1086]
**Describe the bug**
On my production environment, K8S, the memory is not being released resulting in OOM pods and constantly recreating the pods after 1 or 2 pdfs have been generated.
The pdfs contain a lot of images, 200+.

**Environment**
Version : 2024.10.2
OS: arm64

I believe my issues relates to #958 and #968.

I have an example available, but as mentioned. I don't really have issues on my local environment.

**Comment by MarcinZiabek** [comment]
The mentioned issues have already been fixed in previous releases. Could you please share a minimal example?

Please note that 200+ images are many, which may impose higher memory requirements during the generation process.

**Comment by JeremyVm** [comment]
@MarcinZiabek Where can I send you the example?

The PDF's get generated, but the memory does not decrease / release after the generation. If a 2nd or 3rd pdf gets generated, then it'll get OOM and create a new pod.

So increasing the memory is not a solution I believe. It's set at 700 or 750MB.

**Comment by JeremyVm** [comment]
@MarcinZiabek Have you received my example? I've mailed it to contact at questpdf dot com

**Comment by MarcinZiabek** [comment]
Yes, I did! 😄

Thank you for providing the sample code. I have conducted an initial investigation but haven’t identified the root cause yet. As you know, the code is quite complex, and I’m still unsure of the exact source of the issue.

Thank you for your patience!

**Comment by sps-campbellwray** [comment]
> The PDF's get generated, but the memory does not decrease / release after the generation. If a 2nd or 3rd pdf gets generated, then it'll get OOM and create a new pod.

I just wanted to quickly comment to say that I was the one who opened #968 and we're still having issues. I believe it has something to do with the Skia implementation on ARM, as whenever there are images involved QuestPDF doesn't seem to be able to release all of the memory and in our experience it will eventually lead to a crash.

**Comment by troncomputers** [comment]
Same issue for me. For tests I took an example from quick-start and called an API with it in a loop. RAM stayed at 30 - 35% and never dropped. Tested on the latest version. Same behavior without k8s and just in debug mode with VS. Just went at max that it needed and never dropped.

![Image](https://github.com/user-attachments/assets/1d1cac7e-01a8-491f-8919-d6694061c5ff)

**Comment by AntoineGLogaia** [comment]
Same issue here, 
Generating an heavy pdf but without image. ( around 8000 pages)

                               
![Image](https://github.com/user-attachments/assets/c9a71ff0-385c-40e5-aad6-46a9dabe54a7)

On docker production ( x64 arch  ) Memory reach 7.8go for this document

**Comment by MarcinZiabek** [comment]
Over the past two weeks, I have been working on improving memory management in the library. Several significant changes have been implemented, but the most notable is the direct implementation of the IDisposable interface in multiple areas. This change ensures that native memory is released as soon as possible.

Please try the 2025.1.0-rc0 release and provide your feedback.

It's important to note that the library employs lifetime caches. As a result, I do not expect the free memory to return to pre-PDF generation levels. However, memory usage should remain stable and not significantly increase during consecutive generations.

Additionally, please keep in mind that .NET may decide to retain native memory allocations, even if they are not actively in use.

**Comment by troncomputers** [comment]
For me, it didn't help, I still have OOMs for just 6 different types of PDF files, typical ERP system documents, nothing special, with max 2 pages that I called in a loop. Blue spike on the screenshot is when I stress-tested new version

![Image](https://github.com/user-attachments/assets/2d6f8a9a-16c8-4a35-9105-e518c8c48b04)

I tested it with Postman, I made couple different types of documents and continuously ran that in a loop

![Image](https://github.com/user-attachments/assets/65db20d0-2104-40df-be13-da30c708d17b)

**Comment by MarcinZiabek** [comment]
@troncomputers Could you please share a minimal example that could help me reproduce this issue? Also, please share how you stress-test your solution.

**Comment by troncomputers** [comment]
It won't be easy, but I'll try to prepare something

**Comment by MarcinZiabek** [comment]
@troncomputers Thank you for understanding 😄  

I have already improved all obvious aspects related to memory management. However, I want to double-check whether the problem is inside the library or your integration code.

**Comment by EquineSolutions** [comment]
I'm using version 2025.1.1, and I’m noticing that the memory level is properly maintained on my local machine, but it doesn’t seem to work the same way in the Kubernetes pod. This behavior is quite strange. Is there a specific reason for this?

**Comment by MarcinZiabek** [comment]
@EquineSolutions The only significant difference I am aware of is the garbage collector.

Could you please try using the Server GC on your local machine?

https://stackoverflow.com/questions/44035282/how-can-i-enable-server-gc-in-net-core

**Comment by troncomputers** [comment]
@EquineSolutions did you try GC Server? I am not able to reproduce this behavior on small example project with docker, and I am not able to provide the whole project that makes OOMs.

**Comment by JeremyVm** [comment]
> Thank you so much for your feedback, observations and comments. I highly appreciate collaborating with you 😄
> 
> Over the past two weeks, I have been working on improving memory management in the library. Several significant changes have been implemented, but the most notable is the direct implementation of the IDisposable interface in multiple areas. This change ensures that native memory is released as soon as possible.
> 
> Please try the 2025.1.0-rc0 release and provide your feedback.
> 
> It's important to note that the library employs lifetime caches. As a result, I do not expect the free memory to return to pre-PDF generation levels. However, memory usage should remain stable and not significantly increase during consecutive generations.
> 
> Additionally, please keep in mind that .NET may decide to retain native memory allocations, even if they are not actively in use.

Hi Marcin.

My apologies for the late reply. But I haven't been actively working on this project for some weeks now. In the meantime I did decide to switch from an ARM pod to an X64 pod where my api that generates pdf is running on.

The problem is only partially resolved... It now just takes longer before the pod gets evicted due to OOM. So the problem is not just only on ARM but also X64 on K8S.

**Comment by MarcinZiabek** [comment]
In Q1 2025, a significant effort was made to address memory leak issues and optimise memory consumption. Since Q2 2025, we have not received any reports related to memory leak problems, so we are closing this issue. :confirm 

I would like to thank everybody involved in the investigation and testing - your help in making QuestPDF stable and reliable has been invaluable! ❤️
