### ISSUE TITLE
GenerateImages results in a large amount of unmanaged memory

### ISSUE THREAD

**Issue by sps-campbellwray** [QuestPDF/QuestPDF#968]
**Describe the bug**
When calling the `IDocument.GenerateImages()` method there is a large spike in unmanaged memory. On a simple 1-page PDF with no images this results in a spike of approximately 30MB per call. The resulting image `byte[]` is only ~80KB, so this memory must be getting allocated elsewhere.

**To Reproduce**
Can be reproduced with something as simple as:
```
var document = Document.Create(container =>
{
    container.Page(page =>
    {
        page.Size(PageSizes.A4);
        page.Margin(2, Unit.Centimetre);
        page.PageColor(Colors.White);
        page.DefaultTextStyle(x => x.FontSize(20));
    });
}).GenerateImages();
```

If placed inside a for-loop you can see the memory footprint increasing with each invocation.

**Expected behavior**
Unallocated memory should return to normal levels once the images have been generated.

**Screenshots**
From dotMemory, you can clearly see the spike each time `GenerateImages()` is called, this memory will be unallocated when the garbage collector runs, however as this memory is not present on the heap (the heap is only ~20MB) the garbage collector often ignores it until it is too late, resulting in a server crash.
![image](https://github.com/user-attachments/assets/0a431641-57a3-4808-b3dd-424ad1f87648)

**Environment**
What version of the library do you use? 
2024.7.1
What operating system do you use? (OS type, x64 vs x86 vs arm64)
Windows x64 (development)
Linux arm64 (deployed)

**Additional context**
The `GeneratePdf()` endpoint does not have the same issues, so this is something related to how images are generated.

**Comment by sps-campbellwray** [comment]
After some further investigation the issue seems to be with the following block in `ImageCanvas.cs`

```
public override void BeginPage(Size size)
{
    var scalingFactor = Settings.RasterDpi / (float) PageSizes.PointsPerInch;

    Bitmap = new SkBitmap((int) (size.Width * scalingFactor), (int) (size.Height * scalingFactor));
    Canvas = SkCanvas.CreateFromBitmap(Bitmap);
    
    Canvas.Scale(scalingFactor, scalingFactor);
}
```

Specifically the spike in memory occurs right as `new SkBitmap()` is called.

I looks like that SkBitmap might need to be disposed of when the render is done.

**Comment by MarcinZiabek** [comment]
Thank you for finding and sharing this issue 😄  

The memory leak has been fixed in the https://github.com/QuestPDF/QuestPDF/releases/tag/2024.7.2 release. Could you please try it and confirm?

**Comment by sps-campbellwray** [comment]
Ahh, it was the Canvas that needed to be disposed... I spent some time trying to fix this myself, but couldn't figure it out, it's obvious now that I see the solution 😄 

The new version works perfectly, thank you for your help, and for the quick fix!

**Comment by MarcinZiabek** [comment]
Your reasoning about Bitmap was correct. In the native code, Bitmap stores a smart-pointer to the Canvas object. So, as long as the Canvas is not correctly disposed of, the Bitmap is waiting for it, taking memory...

**Comment by sps-campbellwray** [comment]
Hi @MarcinZiabek, 

When I checked earlier I did my testing on Windows and everything was fine, however following a deployment something still isn't quite right. Unfortunately it seems that there might still be a bug when running inside a Docker container.

I have created a minimal API project, with an endpoint that calls the `GenerateImages()` method. The following screenshot shows me doing the following:
1. Take a memory snapshot
2. Calling this endpoint 5 times at approximately 5 second intervals. 
3. Force GC (if you look really closely you can see this at 1m3.5s, it doesn't appear to have had any affect)
4. Take a second memory snapshot
![image](https://github.com/user-attachments/assets/072ba361-fe18-456c-88e6-844f8b4fefc0)

There is still a jump in unmanaged memory, but it appears to be far less deterministic, sometimes the unmanaged memory will increase, other times it won't. The main difference here appears to be that running the garbage collector does not improve the situation, the unmanaged memory remains whether you run GC or not.

I'm not really sure how to debug this further as I cannot properly attach the profiler to the application running in Docker to be able to step through the code and find the problematic area.

I suspect that this bug might not be a Docker one, but a Linux one, so I wonder if runner dotMemory on a Linux machine and debugging that way might help to find the problematic code, I don't have the ability to do this as I don't have any linux machines with a GUI. It is also strange that this bug doesn't affect every OS equally, perhaps it exists within the Skia library or something like that.

Campbell

**Comment by MarcinZiabek** [comment]
Are you working on MacOS? If so, could you please test on the latest version of Rider 2024.2?

I also expect some native memory to be registered and utilized even after document generation. We aim to ensure the usage is consistent and reasonable and does not increase over time.

**Comment by sps-campbellwray** [comment]
Unfortunately not, I am working on Windows with Visual Studio 2022.

I suppose the primary issue is that on Windows the memory will spike when generating images and then immediately come back down, however under Docker the native memory cannot be freed even with excessive use of the garbage collector, so eventually the application will run out of memory and crash. From what I have noticed the memory will increase to 95%+ and just sit there, which means that if a few requests come in simultaneously, or (I believe) given enough sequential requests, it will crash.

I have put together a sample application [QuestPDF.MemoryLeak](https://github.com/sps-campbellwray/QuestPDF.MemoryLeak/tree/main/Source), which I forked from QuestPDF to make it easier to debug.

If you use Docker's `docker stats` command in a separate Terminal window and execute the `GET /pdf` endpoint you should be able to see the memory usage increase with each call. 

I have also added a `/parallel` endpoint that will generate PDFs in parallel to mimic simultaneous API requests, this endpoint could be fixed by implementing a queue, but I mostly added it so that I could contrast how the application runs under Windows (where you can use that endpoint indefinitely, as the memory ceiling returns to normal), compared to Docker where it will crash after only a few batches. 

Finally the `/collect` endpoint is simply used to force garbage collection, it doesn't really have a purpose other than show that the garbage collector is unable to clean up the native memory under Docker.

The following screenshots show the memory usage for 6 requests under both OSes, unfortunately the Docker one is far lower resolution, but it still shows the memory not being released between requests.

Docker - Memory increases and is never released

![image](https://github.com/user-attachments/assets/73bb9a53-45c7-4d29-9318-fc3fb4a0c08c)

Windows - Memory is released immediately

![image](https://github.com/user-attachments/assets/7f21078c-5339-42b6-b0c8-005d1689ad4d)

Thanks again for all of your help with this issue, and if there is anything else I can do to facilitate debugging, please let me know.
